import { Button, Grid } from "semantic-ui-react";
initials = {
  jc: "Julio",
  jd: "Joshua D",
  lf: "Leah",
  af: "Anthony",
  lg: "Leison",
  emh: "Emi",
  jj: "Jake",
  mk: "Michael K",
  tl: "Teo(dor)",
  cm: "Cole M",
  jm: "Joushua M",
  fr: "Faris",
  ms: "Max",
  os: "Om",
  as: "Angela",
  rt: "Richie",
  rv: "Robert(o)",
  az: "Allan",
  tz: "Tony",
  tb: "Theadin",
  tc: "Tyrus",
  yd: "Yichen",
  jud: "Julia",
  ad: "Andrea",
  ee: "Eliot",
  ch: "Cole H",
  ep: "Elisa",
  ar: "Ashir",
  ns: "Nicole",
  gt: "Gavin",
  aw: "Ani",
  sa: "Sahil",
  la: "Laksh(ya)",
  mc: "Michael C",
  ld: "Leo",
  ke: "Kyle",
  pg: "Paola",
  elh: "Ellery",
  eh: "Edwin",
  ih: "Ian",
  hh: "Ian",
  hl: "Henry",
  cn: "Cameron",
  ap: "Arnav",
  cs: "Cici",
  rs: "Cici",
  ay: "Adam",
  ac: "Alex",
  joj: "Johann",
  sp: "Saara",
  mes: "Mehaan",
  kt: "Kaushik",
};
export default function IButton(props) {}
